# .github/workflows/update-hourly.yml

name: Hourly BTC Price Update

on:
  schedule:
    # Run at minute 0 of every hour
    - cron: "0 * * * *"
  workflow_dispatch:  # allows manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pymongo[srv] python-dotenv pandas ta skyfield requests

      - name: Run hourly update
        env:
          # These must match the secrets you added under Settings → Secrets → Actions
          MONGODB_URI:        ${{ secrets.MONGODB_URI }}
          KUCOIN_API_KEY:     ${{ secrets.KUCOIN_API_KEY }}
          KUCOIN_API_SECRET:  ${{ secrets.KUCOIN_API_SECRET }}
          # if you set a passphrase, uncomment the next line
          # KUCOIN_PASSPHRASE:  ${{ secrets.KUCOIN_PASSPHRASE }}
        run: |
          python btc_tracker_mongodb/update_hourly.py
